# Generated by Django 2.2.10 on 2020-03-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juez', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('validado_juez', models.BooleanField(default=False)),
                ('enviado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_juicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_juicio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_resolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_resolucion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poblacion', models.CharField(max_length=70)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juzgado', models.CharField(max_length=70)),
                ('encargado', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=30)),
                ('poblacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Poblacion')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('agno', models.DateField()),
                ('fecha_turno', models.DateField()),
                ('fecha_firma', models.DateField()),
                ('observaciones', models.CharField(max_length=200)),
                ('Juez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Juez')),
                ('estatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Estatus')),
                ('juzgado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Juzgado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captura.Materia')),
                ('tipo_juicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Tipo_juicio')),
                ('tipo_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captura.Tipo_resolucion')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captura.Ubicacion')),
            ],
        ),
    ]
